import type { LevelConfig } from '../types'

// GROUND_Y = 300（CANVAS_HEIGHT 440 - 140）

export const level4Config: LevelConfig = {
  id: 4,
  name: '暗黑城',
  description: '暗精灵的地下王国，波罗丁王的最终要塞',
  minLevel: 15,
  rewardGold: 500,
  rooms: [
    {
      id: 1,
      name: '浅栖之地',
      width: 1400,
      roomType: 'entry',
      bgColor: '#2a1a1a',
      groundColor: '#3a2a2a',
      branches: [2, 4],
      enemies: [
        { type: 'normal', x: 100, y: 280, quantity: 2, spacing: 130, behavior: 'chase' },
        { type: 'elite', x: 400, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 650, y: 280, quantity: 2, spacing: 100, behavior: 'walk' },
        { type: 'elite', x: 950, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 1150, y: 280, quantity: 2, spacing: 80, behavior: 'chase' },
      ],
      obstacles: [
        { type: 'box', x: 300, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
        { type: 'barricade', x: 800, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'spikes', x: 1100, y: 288, width: 50, height: 12, destructible: false },
      ],
      decorations: [
        { type: 'torch', x: 60, y: 250 },
        { type: 'pillar', x: 180, y: 300 },
        { type: 'skull', x: 450, y: 285 },
        { type: 'statue', x: 700, y: 280 },
        { type: 'crystal', x: 900, y: 280 },
        { type: 'chest', x: 1200, y: 275 },
      ],
    },
    {
      id: 2,
      name: '王之遗迹',
      width: 1400,
      roomType: 'boss',
      bgColor: '#4a2a4a',
      groundColor: '#5a3a5a',
      branches: [],
      enemies: [
        { type: 'normal', x: 100, y: 280, quantity: 2, spacing: 130, behavior: 'chase' },
        { type: 'elite', x: 400, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 650, y: 280, quantity: 2, spacing: 100, behavior: 'walk' },
        { type: 'elite', x: 950, y: 280, quantity: 1, behavior: 'chase' },
      ],
      hasBoss: true,
      bossConfig: {
        name: '波罗丁王',
        hp: 100,
        mp: 150,
        width: 72,
        height: 76,
        attackPower: 18,
        speed: 2.5,
        color: '#9C27B0',
        skills: [
          { id: 'boss_melee', name: '王之锤', type: 'melee', cooldown: 1200, damage: 16, range: 60, duration: 500, phaseRequired: 1 },
          { id: 'boss_spread', name: '王之怒', type: 'spread', cooldown: 2500, damage: 14, range: 250, duration: 900, phaseRequired: 1 },
          { id: 'boss_charge', name: '王之突进', type: 'charge', cooldown: 3500, damage: 22, range: 80, duration: 1000, phaseRequired: 2 },
          { id: 'boss_summon', name: '召唤卫兵', type: 'summon', cooldown: 4500, damage: 0, range: 120, duration: 2500, phaseRequired: 3 },
          { id: 'boss_laser', name: '王之光柱', type: 'laser', cooldown: 5500, damage: 25, range: 400, duration: 2500, phaseRequired: 4 },
        ],
        patterns: [
          { type: 'melee', cooldown: 1200, damage: 16, range: 60 },
          { type: 'spread', cooldown: 2500, damage: 14, range: 250 },
          { type: 'charge', cooldown: 3500, damage: 22, range: 80 },
          { type: 'summon', cooldown: 4500, damage: 0, range: 120 },
          { type: 'laser', cooldown: 5500, damage: 25, range: 400, duration: 2500 },
        ],
        maxPhase: 5,
        dropTable: [
          { type: 'gold', chance: 1.0, quantity: 80 },
          { type: 'hpPotion', chance: 0.8, quantity: 5 },
          { type: 'mpPotion', chance: 0.6, quantity: 4 },
          { type: 'equipment', chance: 0.8, quality: 'pink' },
        ],
      },
      obstacles: [
        { type: 'barricade', x: 400, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'box', x: 800, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
      ],
      decorations: [
        { type: 'pillar', x: 80, y: 300 },
        { type: 'statue', x: 300, y: 280 },
        { type: 'torch', x: 550, y: 250 },
        { type: 'throne', x: 700, y: 275 },
        { type: 'statue', x: 1000, y: 280 },
        { type: 'pillar', x: 1250, y: 300 },
      ],
    },
    // 分支：暗黑宝库
    {
      id: 3,
      name: '暗黑秘库',
      width: 900,
      roomType: 'treasure',
      bgColor: '#3a1a1a',
      groundColor: '#4a2a2a',
      branches: [2],
      enemies: [
        { type: 'elite', x: 300, y: 280, quantity: 2, spacing: 200, behavior: 'stationary' },
      ],
      obstacles: [
        { type: 'box', x: 400, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
      ],
      decorations: [
        { type: 'torch', x: 60, y: 250 },
        { type: 'chest', x: 200, y: 275 },
        { type: 'chest', x: 500, y: 275 },
        { type: 'crystal', x: 700, y: 280 },
      ],
      reward: { gold: 120, exp: 80 },
      // 需钥匙解锁
      entryCondition: { type: 'key', itemId: 'dark_key' },
    },
    // 休息房
    {
      id: 4,
      name: '暗黑驿站',
      width: 700,
      roomType: 'rest',
      bgColor: '#1a1a2a',
      groundColor: '#2a2a3a',
      branches: [2],
      enemies: [],
      obstacles: [],
      decorations: [
        { type: 'torch', x: 80, y: 250 },
        { type: 'pillar', x: 200, y: 300 },
        { type: 'throne', x: 400, y: 275 },
        { type: 'statue', x: 550, y: 280 },
      ],
      restEffect: { healPercent: 50, mpRestorePercent: 50 },
    },
  ],
}