// 成就系统配置
import type { Achievement } from '../types'

export const ACHIEVEMENTS: Record<string, Omit<Achievement, 'unlocked' | 'progress'>> = {
  firstStack: {
    id: 'firstStack',
    name: '初出茅庐',
    description: '成功堆叠第一个方块',
    icon: '🏗️',
    target: 1,
  },
  stackMaster: {
    id: 'stackMaster',
    name: '堆叠大师',
    description: '堆叠达到10层',
    icon: '🏆',
    target: 10,
  },
  towerBuilder: {
    id: 'towerBuilder',
    name: '高塔建造者',
    description: '堆叠达到25层',
    icon: '🗼',
    target: 25,
  },
  skyScraper: {
    id: 'skyScraper',
    name: '摩天大楼',
    description: '堆叠达到50层',
    icon: '🏙️',
    target: 50,
  },
  spaceStation: {
    id: 'spaceStation',
    name: '太空站',
    description: '堆叠达到100层',
    icon: '🛸',
    target: 100,
  },
  perfectStart: {
    id: 'perfectStart',
    name: '完美开局',
    description: '连续3次完美对齐',
    icon: '⭐',
    target: 3,
  },
  perfectCombo: {
    id: 'perfectCombo',
    name: '完美连击',
    description: '连续5次完美对齐',
    icon: '✨',
    target: 5,
  },
  perfectStorm: {
    id: 'perfectStorm',
    name: '完美风暴',
    description: '连续10次完美对齐',
    icon: '🌪️',
    target: 10,
  },
  speedDemon: {
    id: 'speedDemon',
    name: '速度恶魔',
    description: '在10秒内完成5次堆叠',
    icon: '⚡',
    target: 5,
  },
  chillMaster: {
    id: 'chillMaster',
    name: '放松大师',
    description: '游戏时长超过5分钟',
    icon: '😌',
    target: 300,
  },
  treasureHunter: {
    id: 'treasureHunter',
    name: '宝藏猎人',
    description: '获得10次奖励方块',
    icon: '💎',
    target: 10,
  },
  luckyStar: {
    id: 'luckyStar',
    name: '幸运之星',
    description: '获得5次幸运方块',
    icon: '🍀',
    target: 5,
  },
  bombSurvivor: {
    id: 'bombSurvivor',
    name: '炸弹幸存者',
    description: '成功躲避3次炸弹方块',
    icon: '💣',
    target: 3,
  },
  weatherWatcher: {
    id: 'weatherWatcher',
    name: '天气观察员',
    description: '经历所有天气类型',
    icon: '🌈',
    target: 5,
  },
  animalFriend: {
    id: 'animalFriend',
    name: '动物之友',
    description: '遇见所有类型的小动物',
    icon: '🐾',
    target: 6,
  },
  powerupCollector: {
    id: 'powerupCollector',
    name: '道具收藏家',
    description: '使用所有类型的道具',
    icon: '🎒',
    target: 9,
  },
  millionaire: {
    id: 'millionaire',
    name: '百万富翁',
    description: '累计获得100000分',
    icon: '💰',
    target: 100000,
  },
  comebackKid: {
    id: 'comebackKid',
    name: '东山再起',
    description: '使用复活道具成功复活',
    icon: '💖',
    target: 1,
  },
}

// 成就解锁奖励
export const ACHIEVEMENT_REWARDS: Record<string, { type: string; amount: number }> = {
  firstStack: { type: 'score', amount: 100 },
  stackMaster: { type: 'score', amount: 500 },
  towerBuilder: { type: 'score', amount: 1000 },
  skyScraper: { type: 'score', amount: 2500 },
  spaceStation: { type: 'score', amount: 10000 },
  perfectStart: { type: 'powerup', amount: 1 },
  perfectCombo: { type: 'powerup', amount: 2 },
  perfectStorm: { type: 'powerup', amount: 3 },
  treasureHunter: { type: 'powerup', amount: 2 },
  luckyStar: { type: 'powerup', amount: 1 },
  millionaire: { type: 'powerup', amount: 5 },
}