import type { LevelConfig } from '../types'

// GROUND_Y = 300（CANVAS_HEIGHT 440 - 140）

export const level2Config: LevelConfig = {
  id: 2,
  name: '天空之城',
  description: '漂浮在空中的魔法都市，通向天界的必经之路',
  minLevel: 5,
  rewardGold: 200,
  rooms: [
    {
      id: 1,
      name: '龙人之塔',
      width: 1200,
      roomType: 'entry',
      bgColor: '#1a1a30',
      groundColor: '#2a2a45',
      branches: [2],
      enemies: [
        { type: 'normal', x: 180, y: 280, quantity: 2, spacing: 100, behavior: 'chase' },
        { type: 'ranged', x: 450, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 650, y: 280, quantity: 2, spacing: 90, behavior: 'walk' },
        { type: 'normal', x: 880, y: 280, quantity: 2, spacing: 80, behavior: 'chase' },
      ],
      obstacles: [
        { type: 'box', x: 350, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
        { type: 'spikes', x: 650, y: 288, width: 50, height: 12, destructible: false },
      ],
      decorations: [
        { type: 'torch', x: 70, y: 250 },
        { type: 'crystal', x: 200, y: 280 },
        { type: 'pillar', x: 450, y: 300 },
        { type: 'statue', x: 550, y: 280 },
        { type: 'barrel', x: 750, y: 275 },
        { type: 'chest', x: 950, y: 275 },
      ],
    },
    {
      id: 2,
      name: '人偶玄关',
      width: 1300,
      roomType: 'normal',
      bgColor: '#151528',
      groundColor: '#252538',
      branches: [3],
      enemies: [
        { type: 'normal', x: 150, y: 280, quantity: 2, spacing: 100, behavior: 'chase' },
        { type: 'ranged', x: 400, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 600, y: 280, quantity: 2, spacing: 90, behavior: 'walk' },
        { type: 'elite', x: 850, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 1050, y: 280, quantity: 2, spacing: 80, behavior: 'chase' },
      ],
      obstacles: [
        { type: 'barricade', x: 300, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'spikes', x: 550, y: 288, width: 50, height: 12, destructible: false },
        { type: 'box', x: 800, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
      ],
      decorations: [
        { type: 'torch', x: 70, y: 250 },
        { type: 'pillar', x: 250, y: 300 },
        { type: 'crystal', x: 450, y: 280 },
        { type: 'statue', x: 650, y: 280 },
        { type: 'banner', x: 850, y: 210 },
      ],
    },
    {
      id: 3,
      name: '石巨人塔',
      width: 1400,
      roomType: 'normal',
      bgColor: '#18182a',
      groundColor: '#28283a',
      branches: [4, 6],
      enemies: [
        { type: 'normal', x: 150, y: 280, quantity: 2, spacing: 100, behavior: 'chase' },
        { type: 'ranged', x: 400, y: 280, quantity: 2, spacing: 150, behavior: 'chase' },
        { type: 'normal', x: 650, y: 280, quantity: 2, spacing: 90, behavior: 'walk' },
        { type: 'elite', x: 900, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 1100, y: 280, quantity: 2, spacing: 80, behavior: 'chase' },
      ],
      obstacles: [
        { type: 'box', x: 300, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
        { type: 'barricade', x: 550, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'spikes', x: 800, y: 288, width: 50, height: 12, destructible: false },
        { type: 'box', x: 1050, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
      ],
      decorations: [
        { type: 'torch', x: 70, y: 250 },
        { type: 'pillar', x: 250, y: 300 },
        { type: 'crystal', x: 450, y: 280 },
        { type: 'statue', x: 650, y: 280 },
        { type: 'barrel', x: 850, y: 275 },
        { type: 'chest', x: 1150, y: 275 },
      ],
    },
    {
      id: 4,
      name: '悬空城',
      width: 1500,
      roomType: 'boss',
      bgColor: '#2a1a40',
      groundColor: '#3a2a50',
      branches: [],
      enemies: [
        { type: 'normal', x: 150, y: 280, quantity: 2, spacing: 100, behavior: 'chase' },
        { type: 'ranged', x: 400, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 600, y: 280, quantity: 2, spacing: 90, behavior: 'chase' },
        { type: 'elite', x: 850, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'ranged', x: 1100, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 1300, y: 280, quantity: 2, spacing: 80, behavior: 'walk' },
      ],
      hasBoss: true,
      bossConfig: {
        name: '光之城主赛格哈特',
        hp: 150,
        mp: 120,
        width: 60,
        height: 64,
        attackPower: 18,
        speed: 2.0,
        color: '#FFD700',
        skills: [
          { id: 'boss_melee', name: '圣光斩', type: 'melee', cooldown: 1000, damage: 18, range: 50, duration: 500, phaseRequired: 1 },
          { id: 'boss_spread', name: '光芒四射', type: 'spread', cooldown: 2000, damage: 14, range: 180, duration: 800, phaseRequired: 1 },
          { id: 'boss_laser', name: '圣光射线', type: 'laser', cooldown: 3000, damage: 22, range: 300, duration: 1500, phaseRequired: 2 },
          { id: 'boss_summon', name: '召唤光球', type: 'summon', cooldown: 4000, damage: 0, range: 150, duration: 2000, phaseRequired: 3 },
        ],
        patterns: [
          { type: 'melee', cooldown: 1000, damage: 18, range: 50 },
          { type: 'spread', cooldown: 2000, damage: 14, range: 180 },
          { type: 'laser', cooldown: 3000, damage: 22, range: 300, duration: 1500 },
          { type: 'summon', cooldown: 4000, damage: 0, range: 150 },
        ],
        maxPhase: 4,
        dropTable: [
          { type: 'gold', chance: 1.0, quantity: 60 },
          { type: 'hpPotion', chance: 0.7, quantity: 3 },
          { type: 'mpPotion', chance: 0.5, quantity: 2 },
          { type: 'equipment', chance: 0.5, quality: 'blue' },
        ],
      },
      obstacles: [
        { type: 'barricade', x: 300, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'box', x: 550, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
        { type: 'barricade', x: 800, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
        { type: 'box', x: 1100, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
      ],
      decorations: [
        { type: 'torch', x: 70, y: 250 },
        { type: 'pillar', x: 250, y: 300 },
        { type: 'banner', x: 450, y: 210 },
        { type: 'statue', x: 650, y: 280 },
        { type: 'window', x: 850, y: 230 },
        { type: 'throne', x: 1200, y: 275 },
      ],
    },
    // 分支：天空宝库
    {
      id: 5,
      name: '天空宝库',
      width: 1000,
      roomType: 'treasure',
      bgColor: '#1a2a40',
      groundColor: '#2a3a55',
      branches: [4],
      enemies: [
        { type: 'normal', x: 200, y: 280, quantity: 2, spacing: 100, behavior: 'chase' },
        { type: 'elite', x: 500, y: 280, quantity: 1, behavior: 'chase' },
        { type: 'normal', x: 750, y: 280, quantity: 2, spacing: 80, behavior: 'chase' },
      ],
      obstacles: [
        { type: 'box', x: 350, y: 272, width: 35, height: 28, destructible: true, hp: 25, state: 'normal' },
        { type: 'barricade', x: 600, y: 276, width: 50, height: 24, destructible: true, hp: 35, state: 'normal' },
      ],
      decorations: [
        { type: 'torch', x: 80, y: 250 },
        { type: 'chest', x: 200, y: 275 },
        { type: 'crystal', x: 400, y: 280 },
        { type: 'statue', x: 600, y: 280 },
        { type: 'chest', x: 800, y: 275 },
      ],
      reward: { gold: 120, exp: 80 },
    },
    {
      id: 6,
      name: '天空休憩地',
      width: 700,
      roomType: 'rest',
      bgColor: '#1a2035',
      groundColor: '#2a3045',
      branches: [4],
      enemies: [],
      obstacles: [],
      decorations: [
        { type: 'torch', x: 80, y: 250 },
        { type: 'pillar', x: 200, y: 300 },
        { type: 'statue', x: 400, y: 280 },
        { type: 'crystal', x: 550, y: 280 },
      ],
      restEffect: { healPercent: 40, mpRestorePercent: 40 },
    },
  ],
}