export const GAME_CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  
  PLAYER: {
    SIZE: 0.4,
    MASS: 1,
    GRAVITY: -0.04,
    CHARGE_DURATION: 2000,
    MIN_VELOCITY: 0.8,
    MAX_VELOCITY: 2.5,
    GROUND_THRESHOLD: 0.1,
    LANDING_SCALE: 0.85,
    IDLE_SCALE: 1,
  },
  
  PLATFORM: {
    BASE_WIDTH: 1.5,
    MIN_WIDTH: 1.0,
    MAX_WIDTH: 2.0,
    DEPTH: 1.5,
    HEIGHT: 0.2,
    BASE_SPACING: 2.5,
    MIN_SPACING: 2.0,
    MAX_SPACING: 4.5,
    HEIGHT_VARIANCE: 1.0,
    ROTATION_VARIANCE: 0.3,
    MAX_ACTIVE: 10,
  },
  
  CAMERA: {
    DISTANCE: 8,
    HEIGHT: 5,
    ANGLE: 60,
    FOLLOW_SPEED: 0.05,
    TARGET_OFFSET: { x: 0, y: 2, z: -3 },
  },
  
  SCORE: {
    BASE: 1,
    PERFECT_BONUS: 2,
    NORMAL_BONUS: 1,
    COMBO_MULTIPLIER_5: 1.2,
    COMBO_MULTIPLIER_10: 1.5,
    PERFECT_THRESHOLD: 0.25,
    EDGE_THRESHOLD: 0.1,
  },
  
  DIFFICULTY: {
    EASY_THRESHOLD: 30,
    MEDIUM_THRESHOLD: 100,
    EASY_SPACING_MULTIPLIER: 0.85,
    MEDIUM_SPACING_MULTIPLIER: 1.0,
    HARD_SPACING_MULTIPLIER: 1.2,
    OBSTACLE_CHANCE_EASY: 0,
    OBSTACLE_CHANCE_MEDIUM: 0.1,
    OBSTACLE_CHANCE_HARD: 0.25,
    MOVING_PLATFORM_CHANCE_EASY: 0,
    MOVING_PLATFORM_CHANCE_MEDIUM: 0.05,
    MOVING_PLATFORM_CHANCE_HARD: 0.15,
  },
  
  WORLD: {
    FALL_THRESHOLD: -20,
    INITIAL_PLATFORMS: 8,
  },
};

export const COLORS = {
  PLAYER: 0x4facfe,
  PLAYER_GLOW: 0x00f2fe,
  PLATFORM_NORMAL: 0xffffff,
  PLATFORM_SPECIAL: 0xa855f7,
  PLATFORM_MOVING: 0x34d399,
  OBSTACLE: 0xef4444,
  BACKGROUND_TOP: 0x87ceeb,
  BACKGROUND_BOTTOM: 0xe0f7fa,
  CLOUD: 0xffffff,
};
