import type { PlayerConfigType } from '../types/players'

const playerConfig: PlayerConfigType = {
  RickDefault: {
    type: 'RickDefault',
    title: '普通瑞克',
    regeneration: 0,
    maximumHitPoints: -20,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol',
    evolutions: ['MemoryRick', 'RickDoofus', 'RickBald', 'TinyRick'],
  },
  CommanderRick: {
    type: 'CommanderRick',
    title: '指挥官瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine3',
    evolutions: [],
  },
  CopRick: {
    type: 'CopRick',
    title: '警察瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol2',
    evolutions: ['RickSupremeGuard'],
  },
  CrowRick: {
    type: 'CrowRick',
    title: '乌鸦瑞克',
    regeneration: 0,
    maximumHitPoints: 300,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'MachineGun3',
    evolutions: [],
  },
  D99Rick: {
    type: 'D99Rick',
    title: 'D-99 瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle3',
    evolutions: [],
  },
  DeepthroatRick: {
    type: 'DeepthroatRick',
    title: '线人瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle2',
    evolutions: ['D99Rick', 'RickGuard'],
  },
  FederationPrisonRick: {
    type: 'FederationPrisonRick',
    title: '囚犯瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol1',
    evolutions: ['CopRick'],
  },
  GeneralRick: {
    type: 'GeneralRick',
    title: '将军瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine2',
    evolutions: ['RickSpaceSuit', 'CommanderRick', 'RickWarrior'],
  },
  GhostcatcherRick: {
    type: 'GhostcatcherRick',
    title: '捉鬼瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun2',
    evolutions: ['RickGuard'],
  },
  MemoryRick: {
    type: 'MemoryRick',
    title: '记忆瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: -1,
    bulletSpeed: 0,
    bulletDamage: 5,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol',
    evolutions: [
      'FederationPrisonRick',
      'RickVapourWave',
      'RickZarchez',
      'PickleRick',
    ],
  },
  PickleRick: {
    type: 'PickleRick',
    title: ' pickle瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RatSuitPickleRick'],
  },
  RaderRick: {
    type: 'RaderRick',
    title: '掠夺者瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun1',
    evolutions: ['GhostcatcherRick'],
  },
  RatSuitPickleRick: {
    type: 'RatSuitPickleRick',
    title: '老鼠装pickle瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver3',
    evolutions: ['SpiritualLeaderRick', 'CrowRick'],
  },
  Rick800: {
    type: 'Rick800',
    title: '瑞克800',
    regeneration: 0,
    maximumHitPoints: 1500,
    bodyDamage: 50,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 100,
    weapon: 'Hand',
    evolutions: [],
  },
  RickBald: {
    type: 'RickBald',
    title: '秃头瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: -1,
    attackRate: 10,
    speed: 0,
    weapon: 'SubmachineGun',
    evolutions: ['WeirdRick', 'RickJunkYard', 'RickFlatTop', 'PickleRick'],
  },
  RickBeefcake: {
    type: 'RickBeefcake',
    title: '肌肉瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['Rick800'],
  },
  RickDoofus: {
    type: 'RickDoofus',
    title: '笨蛋瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 30,
    bulletDamage: 10,
    attackRate: 0.9,
    speed: 0,
    weapon: 'Rifle',
    evolutions: ['WastelandRick', 'SherlockRick', 'RaderRick', 'PickleRick'],
  },
  RickDude: {
    type: 'RickDude',
    title: '酷哥瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster2',
    evolutions: ['RickMiami'],
  },
  RickEvil: {
    type: 'RickEvil',
    title: '邪恶瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol1',
    evolutions: ['RickTurberlent', 'RickShibuya'],
  },
  RickFlatTop: {
    type: 'RickFlatTop',
    title: '平头瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'SubmachineGun1',
    evolutions: ['RickMurderPatrol'],
  },
  RickGreaser: {
    type: 'RickGreaser',
    title: '油头瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken1',
    evolutions: ['RickKarate', 'RickTurberlent'],
  },
  RickGuard: {
    type: 'RickGuard',
    title: '守卫瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun3',
    evolutions: [],
  },
  RickJohnRick: {
    type: 'RickJohnRick',
    title: '约翰瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver3',
    evolutions: [],
  },
  RickJunkYard: {
    type: 'RickJunkYard',
    title: '废土瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine1',
    evolutions: ['GeneralRick'],
  },
  RickKarate: {
    type: 'RickKarate',
    title: '空手道瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken2',
    evolutions: ['RickNinja'],
  },
  RickMiami: {
    type: 'RickMiami',
    title: '迈阿密瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster3',
    evolutions: [],
  },
  RickMurderPatrol: {
    type: 'RickMurderPatrol',
    title: '巡逻瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'SubmachineGun2',
    evolutions: ['RickWarrior'],
  },
  RickNinja: {
    type: 'RickNinja',
    title: '忍者瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken3',
    evolutions: [],
  },
  RickRobot: {
    type: 'RickRobot',
    title: '机器人瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'RocketGun3',
    evolutions: [],
  },
  RickShibuya: {
    type: 'RickShibuya',
    title: '涩谷瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol2',
    evolutions: ['RickRobot', 'Rick800'],
  },
  RickSmooth: {
    type: 'RickSmooth',
    title: '潇洒瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver2',
    evolutions: ['RickJohnRick'],
  },
  RickSpaceSuit: {
    type: 'RickSpaceSuit',
    title: '太空服瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'PlasmoGun3',
    evolutions: [],
  },
  RickSupremeGuard: {
    type: 'RickSupremeGuard',
    title: '至尊守卫瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol3',
    evolutions: [],
  },
  RickSurvivor: {
    type: 'RickSurvivor',
    title: '幸存者瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle2',
    evolutions: ['D99Rick'],
  },
  RickTurberlent: {
    type: 'RickTurberlent',
    title: '湍流汁瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RickNinja', 'RickRobot'],
  },
  RickValentinesDay: {
    type: 'RickValentinesDay',
    title: '情人节约束瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RickBeefcake'],
  },
  RickVapourWave: {
    type: 'RickVapourWave',
    title: '蒸汽波瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 10,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster1',
    evolutions: ['RickDude'],
  },
  RickWarrior: {
    type: 'RickWarrior',
    title: '战士瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'MachineGun3',
    evolutions: [],
  },
  RickZarchez: {
    type: 'RickZarchez',
    title: '扎尔切兹瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver1',
    evolutions: ['RickSmooth'],
  },
  SherlockRick: {
    type: 'SherlockRick',
    title: '夏洛克瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 1,
    bulletDamage: 20,
    attackRate: 0,
    speed: -10,
    weapon: 'Rifle1',
    evolutions: ['DeepthroatRick'],
  },
  SpaceTrooperRick: {
    type: 'SpaceTrooperRick',
    title: '太空步兵瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'PlasmoGun2',
    evolutions: ['RickSpaceSuit'],
  },
  SpiritualLeaderRick: {
    type: 'SpiritualLeaderRick',
    title: '精神领袖瑞克',
    regeneration: 0,
    maximumHitPoints: 300,
    bodyDamage: 10,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: [],
  },
  TinyRick: {
    type: 'TinyRick',
    title: '小不点瑞克',
    regeneration: 0,
    maximumHitPoints: -50,
    bodyDamage: -0.1,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 10,
    speed: 20,
    weapon: 'Pistol',
    evolutions: ['RickGreaser', 'RickEvil', 'RickValentinesDay', 'PickleRick'],
  },
  WastelandRick: {
    type: 'WastelandRick',
    title: '荒野瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle1',
    evolutions: ['RickSurvivor'],
  },
  WeirdRick: {
    type: 'WeirdRick',
    title: '怪异瑞克',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster1',
    evolutions: ['SpaceTrooperRick'],
  },
}

export default playerConfig
