const textConfig = {
  LOADING: '游戏加载中...',
  LOADING_FILES: '正在加载：',
  GAME_OVER: '游戏结束',
  PAUSE: '暂停',
  RESUME: '继续游戏',
  SETTINGS: '设置',
  EXIT: '退出',
  BACK: '返回',
  START: '开始游戏',
  SHOP: '商店',
  NEXT: '下一关',
  RESTART: '重新开始',
  MAIN_MENU: '主菜单',
  MAP_SELECT: '选择地图',
  LEVEL: '等级',
  SCORE: '分数',
  TIME: '时间',
  HEALTH: '生命值',
  EXPERIENCE: '经验值',
  WEAPON: '武器',
  UPGRADE: '升级',
  SKILL_UP: '技能提升',
  SELECT_WEAPON: '选择武器',
  SELECT_SKILL: '选择技能',
  PLAYER_UPGRADE: '角色升级',
  GAME_PAUSED: '游戏暂停',
  PRESS_TO_RESUME: '按 ESC 继续游戏',
}

export default textConfig
