import type { Equipment, Skill, Enemy } from './types'

export const GAME_CONFIG = {
  TILE_SIZE: 1,
  MAP_WIDTH: 40,
  MAP_HEIGHT: 30,
  MAX_LEVELS: 5,
  
  PLAYER_BASE_STATS: {
    hp: 100,
    mp: 50,
    strength: 10,
    agility: 10,
    constitution: 10,
    perception: 10,
    attackSpeed: 1.0,
    moveSpeed: 3.0,
  },
  
  LEVEL_UP_STATS: {
    hp: 20,
    mp: 10,
    strength: 3,
    agility: 2,
    constitution: 3,
    perception: 2,
  },
  
  EXPERIENCE_PER_LEVEL: 100,
  EXPERIENCE_MULTIPLIER: 1.5,
  
  ATTACK_RANGE: 1.5,
  ATTACK_COOLDOWN: 1000,
  
  INVINCIBLE_DURATION: 2000,
  DEATH_PENALTY: 0.1,
  
  CAMERA_HEIGHT: 15,
  CAMERA_DISTANCE: 12,
  CAMERA_MIN_ZOOM: 8,
  CAMERA_MAX_ZOOM: 20,
  CAMERA_ZOOM_SPEED: 0.5,
  
  SKILL_COOLDOWN_REDUCTION: 0.05,
  
  ENEMY_SPAWN_COUNT: {
    level1: 3,
    level2: 5,
    level3: 7,
    level4: 9,
    level5: 12,
  },
  
  ENEMY_STRENGTH_MULTIPLIER: 1.3,
  
  LOOT_CHANCES: {
    equipment: 0.2,
    gold: 0.5,
    potion: 0.3,
    experience: 0.4,
  },
  
  GOLD_REWARD: {
    normal: 10,
    elite: 30,
    boss: 100,
  },
  
  EXPERIENCE_REWARD: {
    normal: 20,
    elite: 50,
    boss: 200,
  },
  
  TRAP_DAMAGE: {
    spike: 15,
    fire: 20,
    ice: 15,
    poison: 10,
  },
  
  TRAP_COOLDOWN: {
    spike: 2000,
    fire: 3000,
    ice: 4000,
    poison: 2500,
  },
  
  CHEST_RARITY_CHANCE: {
    common: 0.7,
    rare: 0.3,
  },
}

export const WEAPON_TEMPLATES: Omit<Equipment, 'id'>[] = [
  { name: 'Iron Sword', type: 'weapon', rarity: 'common', stats: { attack: 8 }, icon: '⚔️', description: 'A basic iron sword.' },
  { name: 'Steel Blade', type: 'weapon', rarity: 'common', stats: { attack: 12 }, icon: '🗡️', description: 'A sturdy steel blade.' },
  { name: 'Sharp Dagger', type: 'weapon', rarity: 'common', stats: { attack: 6, attackSpeed: 0.2 }, icon: '🔪', description: 'Fast but weak.' },
  { name: 'Fire Sword', type: 'weapon', rarity: 'uncommon', stats: { attack: 18, strength: 5 }, icon: '🔥', description: 'Enchanted with fire.' },
  { name: 'Ice Blade', type: 'weapon', rarity: 'uncommon', stats: { attack: 16, agility: 5 }, icon: '❄️', description: 'Chilled with frost.' },
  { name: 'Shadow Dagger', type: 'weapon', rarity: 'uncommon', stats: { attack: 14, attackSpeed: 0.3, perception: 3 }, icon: '🌑', description: 'Strikes from the shadows.' },
  { name: 'Dragon Slayer', type: 'weapon', rarity: 'rare', stats: { attack: 30, strength: 10, perception: 5 }, icon: '🐉', description: 'Legendary dragon slaying sword.' },
  { name: 'Holy Avenger', type: 'weapon', rarity: 'rare', stats: { attack: 28, constitution: 8, maxHp: 20 }, icon: '⚖️', description: 'Blessed by the gods.' },
]

export const ARMOR_TEMPLATES: Omit<Equipment, 'id'>[] = [
  { name: 'Leather Armor', type: 'armor', rarity: 'common', stats: { defense: 5, agility: 3 }, icon: '🥋', description: 'Lightweight leather armor.' },
  { name: 'Iron Armor', type: 'armor', rarity: 'common', stats: { defense: 10, constitution: 2 }, icon: '🛡️', description: 'Heavy iron armor.' },
  { name: 'Chain Mail', type: 'armor', rarity: 'common', stats: { defense: 8 }, icon: '🔗', description: 'Flexible chain mail.' },
  { name: 'Plate Armor', type: 'armor', rarity: 'uncommon', stats: { defense: 18, constitution: 5 }, icon: '🔰', description: 'Full plate armor.' },
  { name: 'Dragon Scale', type: 'armor', rarity: 'uncommon', stats: { defense: 15, maxHp: 30 }, icon: '🐲', description: 'Armor made from dragon scales.' },
  { name: 'Shadow Cloak', type: 'armor', rarity: 'uncommon', stats: { defense: 10, agility: 8 }, icon: '🧥', description: 'Cloak of shadows.' },
  { name: 'Divine Armor', type: 'armor', rarity: 'rare', stats: { defense: 30, constitution: 10, maxHp: 50 }, icon: '✨', description: 'Armor of the divine.' },
  { name: 'Ember Guard', type: 'armor', rarity: 'rare', stats: { defense: 25, strength: 5, maxHp: 40 }, icon: '🔥', description: 'Armor forged in dragon fire.' },
]

export const ACCESSORY_TEMPLATES: Omit<Equipment, 'id'>[] = [
  { name: 'Health Ring', type: 'accessory', rarity: 'common', stats: { maxHp: 15 }, icon: '💍', description: 'A ring that boosts health.' },
  { name: 'Mana Pendant', type: 'accessory', rarity: 'common', stats: { maxMp: 10 }, icon: '📿', description: 'Pendant that increases mana.' },
  { name: 'Strength Bracelet', type: 'accessory', rarity: 'common', stats: { strength: 3 }, icon: '📿', description: 'Bracelet of strength.' },
  { name: 'Agility Boots', type: 'accessory', rarity: 'uncommon', stats: { agility: 5, moveSpeed: 0.5 }, icon: '👢', description: 'Boots that increase speed.' },
  { name: 'Crit Earring', type: 'accessory', rarity: 'uncommon', stats: { perception: 5, attack: 5 }, icon: '💎', description: 'Earring that increases crit chance.' },
  { name: 'Vitality Amulet', type: 'accessory', rarity: 'uncommon', stats: { constitution: 5, maxHp: 20 }, icon: '🔮', description: 'Amulet of vitality.' },
  { name: 'Ancient Relic', type: 'accessory', rarity: 'rare', stats: { strength: 8, agility: 8, constitution: 8, perception: 8 }, icon: '🏺', description: 'An ancient mystical relic.' },
  { name: 'Phoenix Feather', type: 'accessory', rarity: 'rare', stats: { maxHp: 50, maxMp: 30 }, icon: '🪶', description: 'Feather from a legendary phoenix.' },
]

export const SKILL_TEMPLATES: Omit<Skill, 'id'>[] = [
  { name: 'Basic Attack', icon: '⚔️', level: 1, maxLevel: 5, cooldown: 0, currentCooldown: 0, damage: 1.0, manaCost: 0, description: 'Basic melee attack.', unlocked: true },
  { name: 'Power Strike', icon: '💥', level: 1, maxLevel: 5, cooldown: 5000, currentCooldown: 0, damage: 2.5, manaCost: 15, description: 'Powerful strike dealing 250% damage.', unlocked: false },
  { name: 'Whirlwind', icon: '🌀', level: 1, maxLevel: 5, cooldown: 8000, currentCooldown: 0, damage: 1.5, manaCost: 20, description: 'Attack all nearby enemies.', unlocked: false },
  { name: 'Heal', icon: '💚', level: 1, maxLevel: 5, cooldown: 10000, currentCooldown: 0, damage: 0, manaCost: 30, description: 'Heal 30% of max HP.', unlocked: false },
  { name: 'Sprint', icon: '⚡', level: 1, maxLevel: 5, cooldown: 12000, currentCooldown: 0, damage: 0, manaCost: 10, description: 'Increase movement speed by 100% for 3 seconds.', unlocked: false },
]

export const ENEMY_TEMPLATES: Omit<Enemy, 'id' | 'position' | 'rotation'>[] = [
  {
    type: 'normal',
    name: 'Goblin',
    size: { width: 0.8, height: 1.2, depth: 0.8 },
    hp: 30,
    maxHp: 30,
    attack: 8,
    defense: 2,
    speed: 2.0,
    attackRange: 1.2,
    aggroRange: 5,
    behavior: 'patrol',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 8,
    score: 100,
    lootTable: [],
    isBoss: false,
    phase: 1,
    maxPhase: 1,
    attackPatterns: ['melee'],
    currentPattern: 0,
  },
  {
    type: 'normal',
    name: 'Skeleton',
    size: { width: 0.7, height: 1.4, depth: 0.7 },
    hp: 25,
    maxHp: 25,
    attack: 10,
    defense: 3,
    speed: 1.8,
    attackRange: 1.5,
    aggroRange: 6,
    behavior: 'patrol',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 10,
    score: 120,
    lootTable: [],
    isBoss: false,
    phase: 1,
    maxPhase: 1,
    attackPatterns: ['melee'],
    currentPattern: 0,
  },
  {
    type: 'elite',
    name: 'Orc Warrior',
    size: { width: 1.2, height: 1.6, depth: 1.2 },
    hp: 80,
    maxHp: 80,
    attack: 18,
    defense: 8,
    speed: 2.2,
    attackRange: 1.5,
    aggroRange: 7,
    behavior: 'patrol',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 18,
    score: 300,
    lootTable: [],
    isBoss: false,
    phase: 1,
    maxPhase: 1,
    attackPatterns: ['melee', 'charge'],
    currentPattern: 0,
  },
  {
    type: 'elite',
    name: 'Dark Mage',
    size: { width: 0.9, height: 1.5, depth: 0.9 },
    hp: 60,
    maxHp: 60,
    attack: 25,
    defense: 4,
    speed: 1.5,
    attackRange: 4,
    aggroRange: 8,
    behavior: 'idle',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 25,
    score: 350,
    lootTable: [],
    isBoss: false,
    phase: 1,
    maxPhase: 1,
    attackPatterns: ['ranged'],
    currentPattern: 0,
  },
]

export const BOSS_TEMPLATES: Omit<Enemy, 'id' | 'position' | 'rotation'>[] = [
  {
    type: 'boss',
    name: 'Goblin King',
    size: { width: 2.0, height: 2.5, depth: 2.0 },
    hp: 200,
    maxHp: 200,
    attack: 30,
    defense: 15,
    speed: 1.5,
    attackRange: 2,
    aggroRange: 10,
    behavior: 'idle',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 30,
    score: 2000,
    lootTable: [],
    isBoss: true,
    phase: 1,
    maxPhase: 2,
    attackPatterns: ['melee', 'aoe', 'summon'],
    currentPattern: 0,
  },
  {
    type: 'boss',
    name: 'Lich Lord',
    size: { width: 1.8, height: 3.0, depth: 1.8 },
    hp: 350,
    maxHp: 350,
    attack: 45,
    defense: 20,
    speed: 1.2,
    attackRange: 5,
    aggroRange: 12,
    behavior: 'idle',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 45,
    score: 3500,
    lootTable: [],
    isBoss: true,
    phase: 1,
    maxPhase: 3,
    attackPatterns: ['ranged', 'aoe', 'summon', 'teleport'],
    currentPattern: 0,
  },
  {
    type: 'boss',
    name: 'Dragon Wyrm',
    size: { width: 3.0, height: 4.0, depth: 3.0 },
    hp: 500,
    maxHp: 500,
    attack: 60,
    defense: 30,
    speed: 1.8,
    attackRange: 3,
    aggroRange: 15,
    behavior: 'idle',
    lastAttackTime: 0,
    patrolPoints: [],
    currentPatrolIndex: 0,
    damage: 60,
    score: 5000,
    lootTable: [],
    isBoss: true,
    phase: 1,
    maxPhase: 3,
    attackPatterns: ['melee', 'breath', 'stomp', 'tail'],
    currentPattern: 0,
  },
]

export const LEVEL_DESIGN = {
  1: {
    name: '新手初探',
    difficulty: 'easy',
    roomCount: 4,
    enemyCount: 3,
    trapCount: 0,
    chestCount: 2,
    hasBoss: false,
    bossIndex: -1,
  },
  2: {
    name: '地牢进阶',
    difficulty: 'normal',
    roomCount: 6,
    enemyCount: 5,
    trapCount: 3,
    chestCount: 3,
    hasBoss: false,
    bossIndex: -1,
  },
  3: {
    name: '机关迷城',
    difficulty: 'medium',
    roomCount: 8,
    enemyCount: 7,
    trapCount: 6,
    chestCount: 4,
    hasBoss: true,
    bossIndex: 0,
  },
  4: {
    name: '深渊险境',
    difficulty: 'hard',
    roomCount: 10,
    enemyCount: 9,
    trapCount: 8,
    chestCount: 4,
    hasBoss: true,
    bossIndex: 1,
  },
  5: {
    name: '终极深渊',
    difficulty: 'extreme',
    roomCount: 12,
    enemyCount: 12,
    trapCount: 10,
    chestCount: 5,
    hasBoss: true,
    bossIndex: 2,
  },
}

export const COLORS = {
  floor: 0x3a3a3a,
  wall: 0x5a5a5a,
  wallDark: 0x2a2a2a,
  door: 0x8b4513,
  chest: 0xffd700,
  chestRare: 0x00ff88,
  trap: 0xff4444,
  switch: 0x44ff44,
  stairs: 0x8888ff,
  player: 0x4488ff,
  enemy: 0xff4444,
  enemyElite: 0xffaa00,
  enemyBoss: 0xff0066,
  damage: 0xff4444,
  critical: 0xff00ff,
  heal: 0x44ff44,
  mana: 0x4488ff,
  gold: 0xffd700,
  common: 0xaaaaaa,
  uncommon: 0x00ff88,
  rare: 0x4488ff,
}

export const SOUND_EFFECTS = {
  attack: 'sfx_attack',
  hit: 'sfx_hit',
  death: 'sfx_death',
  pickup: 'sfx_pickup',
  chest: 'sfx_chest',
  door: 'sfx_door',
  trap: 'sfx_trap',
  levelUp: 'sfx_levelup',
  skill: 'sfx_skill',
  damage: 'sfx_damage',
  heal: 'sfx_heal',
}

export const UI_CONFIG = {
  healthBarWidth: 200,
  healthBarHeight: 20,
  manaBarWidth: 200,
  manaBarHeight: 12,
  expBarWidth: 200,
  expBarHeight: 8,
  minimapSize: 150,
  skillIconSize: 50,
  inventorySlotSize: 60,
  notificationDuration: 3000,
}

export const CONTROLS = {
  keyboard: {
    up: ['ArrowUp', 'KeyW'],
    down: ['ArrowDown', 'KeyS'],
    left: ['ArrowLeft', 'KeyA'],
    right: ['ArrowRight', 'KeyD'],
    attack: ['MouseLeft'],
    skill: ['Space'],
    interact: ['KeyE'],
    reset: ['KeyR'],
    zoomIn: ['NumpadAdd', 'Equal'],
    zoomOut: ['NumpadSubtract', 'Minus'],
    inventory: ['KeyI'],
    map: ['KeyM'],
    skills: ['KeyK'],
  },
  touch: {
    joystickSize: 100,
    buttonSize: 70,
    buttonOffset: 80,
  },
}