import { Question } from './types';

export const GAME_CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  
  TIME_LIMITS: {
    1: 60,
    2: 50,
    3: 45,
    4: 40,
    5: 35,
  },
  
  PASS_SCORE: 50,
  
  TIME_BONUS: {
    threshold: 20,
    multiplier: 2,
  },
  
  MAP: {
    LAT_MIN: 18,
    LAT_MAX: 54,
    LNG_MIN: 73,
    LNG_MAX: 135,
    CENTER_LAT: 35.86,
    CENTER_LNG: 104.19,
  },
  
  CAMERA: {
    MIN_ZOOM: 2,
    MAX_ZOOM: 15,
    INITIAL_ZOOM: 5,
    ROTATION_SENSITIVITY: 0.005,
    ZOOM_SENSITIVITY: 0.002,
  },
  
  SCORE: {
    PERFECT_THRESHOLD: 200,
    EXCELLENT_THRESHOLD: 500,
    GOOD_THRESHOLD: 1000,
    PERFECT_SCORE: 100,
    EXCELLENT_SCORE: 80,
    GOOD_SCORE: 60,
  },
};

export const QUESTIONS: Question[] = [
  {
    id: 'prov-1',
    type: 'province',
    difficulty: 1,
    name: '新疆维吾尔自治区',
    hint: '中国陆地面积最大的省级行政区',
    target: { lat: 41.15, lng: 85.32 },
    tolerance: 3,
    knowledge: '新疆是中国陆地面积最大的省级行政区，面积约166万平方公里，占全国总面积的六分之一。新疆地域辽阔，拥有丰富的自然资源和多样的民族文化。',
  },
  {
    id: 'prov-2',
    type: 'province',
    difficulty: 1,
    name: '西藏自治区',
    hint: '世界屋脊，平均海拔最高的地区',
    target: { lat: 31.5, lng: 91.1 },
    tolerance: 3,
    knowledge: '西藏自治区位于中国西南部，平均海拔超过4000米，被誉为"世界屋脊"。拥有布达拉宫等著名文化遗产和壮丽的自然风光。',
  },
  {
    id: 'prov-3',
    type: 'province',
    difficulty: 1,
    name: '内蒙古自治区',
    hint: '中国跨越经度最广的省级行政区',
    target: { lat: 41.9, lng: 111.7 },
    tolerance: 3,
    knowledge: '内蒙古自治区是中国跨越经度最广的省级行政区，拥有广袤的草原和丰富的矿产资源，是中国重要的畜牧业基地。',
  },
  {
    id: 'prov-4',
    type: 'province',
    difficulty: 1,
    name: '广东省',
    hint: '中国经济最发达的省份之一，南临南海',
    target: { lat: 23.13, lng: 113.26 },
    tolerance: 2,
    knowledge: '广东省位于中国南部沿海，是中国改革开放的前沿阵地，经济总量连续多年位居全国第一，拥有广州、深圳等国际化大都市。',
  },
  {
    id: 'prov-5',
    type: 'province',
    difficulty: 2,
    name: '四川省',
    hint: '天府之国，大熊猫的故乡',
    target: { lat: 30.57, lng: 104.06 },
    tolerance: 2,
    knowledge: '四川省位于中国西南部，素有"天府之国"美誉。这里是大熊猫的故乡，拥有九寨沟、都江堰等著名旅游景点。',
  },
  {
    id: 'prov-6',
    type: 'province',
    difficulty: 2,
    name: '云南省',
    hint: '彩云之南，少数民族最多的省份',
    target: { lat: 24.89, lng: 102.83 },
    tolerance: 2,
    knowledge: '云南省位于中国西南边陲，是中国少数民族种类最多的省份，拥有25个少数民族。这里自然风光秀丽，民族风情浓郁。',
  },
  {
    id: 'prov-7',
    type: 'province',
    difficulty: 2,
    name: '黑龙江省',
    hint: '中国最北端的省份，冰雪之乡',
    target: { lat: 45.8, lng: 126.63 },
    tolerance: 2,
    knowledge: '黑龙江省位于中国最北端，冬季漫长寒冷，是著名的冰雪旅游胜地。拥有大兴安岭原始森林和广阔的黑土地。',
  },
  {
    id: 'prov-8',
    type: 'province',
    difficulty: 2,
    name: '山东省',
    hint: '孔孟之乡，黄河入海口',
    target: { lat: 36.6, lng: 116.98 },
    tolerance: 2,
    knowledge: '山东省位于中国东部沿海，是儒家文化的发源地，拥有泰山、曲阜三孔等著名文化遗产，黄河在此注入渤海。',
  },
  {
    id: 'city-1',
    type: 'city',
    difficulty: 2,
    name: '北京市',
    hint: '中国首都，政治文化中心',
    target: { lat: 39.9, lng: 116.4 },
    tolerance: 0.5,
    knowledge: '北京是中华人民共和国首都，是中国的政治、文化中心，拥有故宫、天安门广场、长城等众多历史文化古迹。',
  },
  {
    id: 'city-2',
    type: 'city',
    difficulty: 2,
    name: '上海市',
    hint: '中国经济中心，国际化大都市',
    target: { lat: 31.23, lng: 121.47 },
    tolerance: 0.5,
    knowledge: '上海是中国最大的经济中心和国际化大都市，拥有外滩、陆家嘴等标志性建筑，是中国对外开放的重要窗口。',
  },
  {
    id: 'city-3',
    type: 'city',
    difficulty: 2,
    name: '广州市',
    hint: '华南地区中心城市，千年商都',
    target: { lat: 23.13, lng: 113.26 },
    tolerance: 0.5,
    knowledge: '广州是广东省省会，是华南地区的政治、经济、文化中心，素有"千年商都"之称，是中国重要的对外贸易港口。',
  },
  {
    id: 'city-4',
    type: 'city',
    difficulty: 3,
    name: '成都市',
    hint: '四川省省会，休闲美食之都',
    target: { lat: 30.57, lng: 104.06 },
    tolerance: 0.5,
    knowledge: '成都是四川省省会，被誉为"天府之国"的中心，以悠闲的生活节奏和丰富的美食文化闻名于世。',
  },
  {
    id: 'city-5',
    type: 'city',
    difficulty: 3,
    name: '武汉市',
    hint: '九省通衢，中部地区中心城市',
    target: { lat: 30.59, lng: 114.31 },
    tolerance: 0.5,
    knowledge: '武汉是湖北省省会，位于长江中游，素有"九省通衢"之称，是中国中部地区的重要交通枢纽和工业基地。',
  },
  {
    id: 'city-6',
    type: 'city',
    difficulty: 3,
    name: '西安市',
    hint: '十三朝古都，丝绸之路起点',
    target: { lat: 34.27, lng: 108.95 },
    tolerance: 0.5,
    knowledge: '西安是陕西省省会，是中华文明的重要发祥地，曾是周、秦、汉、唐等十三个朝代的都城，是古丝绸之路的起点。',
  },
  {
    id: 'terrain-1',
    type: 'terrain',
    difficulty: 3,
    name: '珠穆朗玛峰',
    hint: '世界最高峰，海拔8848.86米',
    target: { lat: 27.98, lng: 86.92 },
    tolerance: 0.5,
    knowledge: '珠穆朗玛峰是世界最高峰，海拔8848.86米，位于中国与尼泊尔边界。它是喜马拉雅山脉的主峰，被誉为"世界第三极"。',
  },
  {
    id: 'terrain-2',
    type: 'terrain',
    difficulty: 3,
    name: '长江',
    hint: '中国第一长河，世界第三长河',
    target: { lat: 30.5, lng: 121.5 },
    tolerance: 1,
    knowledge: '长江是中国第一长河，全长约6300公里，是世界第三长河。它发源于青藏高原，流经11个省市，最终注入东海。',
  },
  {
    id: 'terrain-3',
    type: 'terrain',
    difficulty: 3,
    name: '黄河',
    hint: '中国第二长河，中华文明母亲河',
    target: { lat: 35.0, lng: 110.0 },
    tolerance: 1,
    knowledge: '黄河是中国第二长河，全长约5464公里。它是中华文明的摇篮，孕育了灿烂的华夏文明，被誉为"母亲河"。',
  },
  {
    id: 'terrain-4',
    type: 'terrain',
    difficulty: 4,
    name: '青藏高原',
    hint: '世界屋脊，地球第三极',
    target: { lat: 33.0, lng: 94.0 },
    tolerance: 2,
    knowledge: '青藏高原是世界上最高的高原，平均海拔超过4000米，被誉为"世界屋脊"和"地球第三极"。它是长江、黄河等多条大河的发源地。',
  },
  {
    id: 'terrain-5',
    type: 'terrain',
    difficulty: 4,
    name: '黄山',
    hint: '天下第一奇山，著名旅游胜地',
    target: { lat: 30.14, lng: 118.18 },
    tolerance: 0.3,
    knowledge: '黄山位于安徽省，以奇松、怪石、云海、温泉"四绝"闻名于世，被誉为"天下第一奇山"，是中国著名的风景名胜区。',
  },
  {
    id: 'terrain-6',
    type: 'terrain',
    difficulty: 4,
    name: '洞庭湖',
    hint: '中国第二大淡水湖',
    target: { lat: 29.3, lng: 112.5 },
    tolerance: 0.5,
    knowledge: '洞庭湖位于湖南省北部，是中国第二大淡水湖。它是长江流域重要的调蓄湖泊，对长江防洪具有重要作用。',
  },
  {
    id: 'border-1',
    type: 'border',
    difficulty: 4,
    name: '漠河',
    hint: '中国最北端的城市',
    target: { lat: 53.5, lng: 122.3 },
    tolerance: 0.5,
    knowledge: '漠河市位于黑龙江省北部，是中国纬度最高的城市，也是中国最北端的城市。这里有"北极村"，是观赏极光的好地方。',
  },
  {
    id: 'border-2',
    type: 'border',
    difficulty: 4,
    name: '曾母暗沙',
    hint: '中国领土最南端',
    target: { lat: 4.15, lng: 112.3 },
    tolerance: 0.5,
    knowledge: '曾母暗沙位于南海，是中国领土的最南端。它是一座水下珊瑚礁，自古以来就是中国领土不可分割的一部分。',
  },
  {
    id: 'border-3',
    type: 'border',
    difficulty: 5,
    name: '黑龙江主航道中心线',
    hint: '中国最东端，与俄罗斯隔江相望',
    target: { lat: 48.3, lng: 135.1 },
    tolerance: 0.5,
    knowledge: '黑龙江主航道中心线是中国与俄罗斯的界河，位于黑龙江省抚远市的黑龙江与乌苏里江交汇处是中国领土的最东端。',
  },
  {
    id: 'border-4',
    type: 'border',
    difficulty: 5,
    name: '帕米尔高原',
    hint: '中国领土最西端',
    target: { lat: 39.3, lng: 73.5 },
    tolerance: 0.5,
    knowledge: '帕米尔高原位于新疆西南部，是中国领土的最西端。这里群山连绵，是古代丝绸之路的重要通道。',
  },
  {
    id: 'border-5',
    type: 'border',
    difficulty: 5,
    name: '喀什',
    hint: '中国最西端的城市',
    target: { lat: 39.4, lng: 75.9 },
    tolerance: 0.3,
    knowledge: '喀什市位于新疆西南部，是中国最西端的城市，也是古丝绸之路的重要驿站，具有独特的西域风情。',
  },
];

export const PROVINCE_COLORS: { [key: string]: number } = {
  '北京市': 0xffe4c4,
  '天津市': 0xffe4c4,
  '河北省': 0xf0e68c,
  '山西省': 0xdda0dd,
  '内蒙古自治区': 0x90ee90,
  '辽宁省': 0x87ceeb,
  '吉林省': 0x87ceeb,
  '黑龙江省': 0x87ceeb,
  '上海市': 0xffe4c4,
  '江苏省': 0xffa500,
  '浙江省': 0xffa500,
  '安徽省': 0xdda0dd,
  '福建省': 0x98fb98,
  '江西省': 0xdda0dd,
  '山东省': 0xf0e68c,
  '河南省': 0xf0e68c,
  '湖北省': 0x98fb98,
  '湖南省': 0x98fb98,
  '广东省': 0xff69b4,
  '广西壮族自治区': 0x98fb98,
  '海南省': 0xff69b4,
  '重庆市': 0xdda0dd,
  '四川省': 0x90ee90,
  '贵州省': 0x98fb98,
  '云南省': 0x90ee90,
  '西藏自治区': 0xfff4e5,
  '陕西省': 0xf0e68c,
  '甘肃省': 0xf5deb3,
  '青海省': 0xfff4e5,
  '宁夏回族自治区': 0xf5deb3,
  '新疆维吾尔自治区': 0xf5deb3,
  '香港特别行政区': 0xffd700,
  '澳门特别行政区': 0xffd700,
  '台湾省': 0xff69b4,
};

export const COLORS = {
  MAP_BASE: 0x2d5a27,
  MAP_HIGHLIGHT: 0x4a7c59,
  PLAYER_MARKER: 0x3498db,
  TARGET_MARKER: 0x2ecc71,
  BORDERS: 0xffffff,
  BACKGROUND_TOP: 0x87ceeb,
  BACKGROUND_BOTTOM: 0xe0f7fa,
  UI_TEXT: 0x333333,
  UI_ACCENT: 0x3498db,
  SUCCESS: 0x2ecc71,
  FAIL: 0xe74c3c,
};
