export { initEliminate } from './eliminate/index'
export { initDodge } from './dodge/index'
export { initColorSort } from './colorSort/index'  // 新版色彩排序（10关卡系统）
// export { initSort } from './sort'  // 旧版已废弃，使用 initColorSort
export { initPop } from './pop/index'
export { initFruitSlice } from './fruitSlice/index'
export { initBouncePath } from './bouncePath/index'
export { initNeonRun } from './neonRun/index'
export { initTetris } from './tetris/index'
export { initAnimalMatch } from './animalMatch/index'
export { initStack } from './stack/index'
export { initSpaceShooter } from './spaceshooter'
export { initTowerDefense } from './towerDefense'
export { initMemoryMatch } from './memoryMatch/index'
export { initSnake } from './snake/index'
export { initWhackMole } from './whackMole/index'
export { initRacingRun } from './racingRun'
export { initRpgShooter } from './rpgShooter/index'
export { initRpgShooterTD } from './rpgShooterTowerDefense/init'
export { initDragonShooter } from './dragonShooter/index'
export { initCookieCut } from './cookieCut/index'
export { initBubbleShooter } from './bubbleShooter/index'
export { initContraRpg } from './contraRpg/index'
export { initWangzheRpg } from './wangzheRpg/index'
export { initDnfRpg } from './dnfRpg/index'
// export { initCloudRunner } from './cloudRunner/index'  // 模块尚未实现
// export { initSkyDefense } from './skyDefense/index'    // 模块尚未实现
